
import React, { createContext, useContext, useState, useEffect } from "react";

type Currency = "EUR" | "USD" | "XOF";
export type Language = "fr" | "en" | "es" | "wo";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  currency: Currency;
  setCurrency: (currency: Currency) => void;
  t: (key: string) => string;
}

const languageMap: Record<Language, string> = {
  fr: "Français",
  en: "English",
  es: "Español",
  wo: "Wolof",
};

const currencyMap: Record<Language, Currency> = {
  fr: "EUR",
  en: "USD",
  es: "EUR",
  wo: "XOF",
};

const currencySymbols: Record<Currency, string> = {
  EUR: "€",
  USD: "$",
  XOF: "FCFA",
};

const translations: Record<Language, Record<string, string>> = {
  fr: {
    "home.title": "Créez un CV professionnel en quelques clics",
    "home.subtitle": "Une plateforme interactive qui vous aide à créer un CV professionnel adapté aux exigences des recruteurs",
    "home.cta.start": "Commencer gratuitement",
    "home.cta.modify": "Modifier un CV existant",
    "templates.title": "Explorez nos modèles de CV",
    "templates.subtitle": "Découvrez notre collection complète de modèles professionnels et créatifs pour faire briller votre CV",
    "templates.search": "Rechercher un modèle...",
    "templates.category.all": "Tous",
    "templates.category.professional": "Professionnels",
    "templates.category.creative": "Créatifs",
    "templates.category.business": "Business",
    "templates.category.academic": "Académiques",
    "templates.category.minimalist": "Minimalistes",
    "templates.category.colorful": "Colorés",
    "templates.category.modern": "Modernes",
    "templates.popular": "Populaire",
    "templates.use": "Utiliser ce modèle",
    "templates.notfound": "Aucun modèle trouvé",
    "templates.notfound.subtitle": "Essayez d'autres termes de recherche ou filtres",
    "builder.title": "Créez votre CV",
    "builder.subtitle": "Utilisez notre éditeur pour créer un CV professionnel en quelques minutes",
    "builder.editor": "Éditeur",
    "builder.preview": "Aperçu",
    "builder.save": "Sauvegarder",
    "builder.download": "Télécharger PDF",
    "builder.sections": "Sections",
    "builder.sections.subtitle": "Ajoutez ou modifiez les sections de votre CV",
    "builder.add.section": "Ajouter une section",
    "builder.personal": "Informations personnelles",
    "builder.experience": "Expérience professionnelle",
    "builder.education": "Formation",
    "builder.skills": "Compétences",
    "builder.languages": "Langues",
    "builder.interests": "Centres d'intérêt",
    "builder.preview.title": "Aperçu de votre CV",
    "builder.preview.subtitle": "Voici comment votre CV apparaîtra une fois téléchargé",
    "modify.title": "Modifier un CV existant",
    "modify.subtitle": "Téléchargez votre CV existant pour le transformer avec notre éditeur",
    "modify.upload": "Télécharger votre CV",
    "modify.formats": "Formats acceptés: PDF, Word (.docx, .doc)",
    "modify.drop": "Glissez-déposez votre CV ici ou cliquez pour le sélectionner",
    "modify.maxsize": "Taille maximale: 5MB",
    "modify.browse": "Parcourir les fichiers",
    "modify.upload.btn": "Télécharger",
    "modify.uploading": "Téléchargement en cours...",
    "modify.success": "Téléchargement réussi !",
    "modify.success.message": "Votre CV a été téléchargé avec succès. Nous sommes en train d'analyser son contenu.",
    "modify.redirect": "Redirection vers l'éditeur de CV dans quelques secondes...",
    "modify.error.size": "Le fichier est trop volumineux. La taille maximale est de 5MB.",
    "modify.error.format": "Format de fichier non supporté. Veuillez télécharger un fichier PDF ou Word.",
    "how.title": "Comment ça marche",
    "how.step1": "Téléchargez votre CV",
    "how.step1.desc": "Téléchargez votre CV existant au format PDF ou Word.",
    "how.step2": "Notre système l'analyse",
    "how.step2.desc": "Notre outil intelligent extrait automatiquement les informations de votre CV.",
    "how.step3": "Personnalisez et améliorez",
    "how.step3.desc": "Utilisez notre éditeur pour modifier, améliorer et choisir un nouveau design.",
    "howworks.title": "Comment ça marche ?",
    "howworks.description": "Réalisez un CV parfait grâce à nos modèles et à leurs mises en page professionnelles.",
    "howworks.step1.title": "Sélectionnez un modèle de CV",
    "howworks.step1.description": "parmi nos 35 modèles personnalisables.",
    "howworks.step2.title": "Ajoutez des contenus pré-rédigés",
    "howworks.step2.description": "par des experts (plus de 58 000 contenus disponibles).",
    "howworks.step3.title": "Téléchargez au format PDF ou Word",
    "howworks.step3.description": "et commencez à postuler.",
    "pricing.title": "Tarifs simples et transparents",
    "pricing.subtitle": "Choisissez le plan qui correspond à vos besoins, sans mauvaises surprises.",
    "pricing.monthly": "Mensuel",
    "pricing.yearly": "Annuel",
    "pricing.discount": "(-20%)",
    "pricing.popular": "Le plus populaire",
    "pricing.free": "Gratuit",
    "pricing.free.desc": "Pour commencer avec les bases",
    "pricing.premium": "Premium",
    "pricing.premium.desc": "Pour les demandeurs d'emploi sérieux",
    "pricing.student": "Étudiant",
    "pricing.student.desc": "Spécial pour étudiants avec carte",
    "pricing.per.month": "par mois",
    "pricing.yearly.save": "Économisez 20% avec l'abonnement annuel",
    "pricing.free.btn": "Commencer gratuitement",
    "pricing.premium.btn": "S'abonner maintenant",
    "pricing.student.btn": "Vérifier éligibilité",
    "pricing.included": "Inclus dans ce plan :",
    "pricing.limitations": "Limitations :",
    "pricing.faq.title": "Questions fréquentes",
    "pricing.faq.more": "Plus d'informations disponibles dans notre centre d'aide.",
    "pricing.faq.others": "Vous avez d'autres questions ? Contactez notre équipe de support.",
    "pricing.faq.contact": "Contacter le support",
    "footer.copyright": "Tous droits réservés",
  },
  en: {
    "home.title": "Create a professional CV in a few clicks",
    "home.subtitle": "An interactive platform that helps you create a professional CV tailored to recruiters' requirements",
    "home.cta.start": "Start for free",
    "home.cta.modify": "Modify an existing CV",
    "templates.title": "Explore our CV templates",
    "templates.subtitle": "Discover our complete collection of professional and creative templates to make your CV shine",
    "templates.search": "Search for a template...",
    "templates.category.all": "All",
    "templates.category.professional": "Professional",
    "templates.category.creative": "Creative",
    "templates.category.business": "Business",
    "templates.category.academic": "Academic",
    "templates.category.minimalist": "Minimalist",
    "templates.category.colorful": "Colorful",
    "templates.category.modern": "Modern",
    "templates.popular": "Popular",
    "templates.use": "Use this template",
    "templates.notfound": "No templates found",
    "templates.notfound.subtitle": "Try other search terms or filters",
    "builder.title": "Create your CV",
    "builder.subtitle": "Use our editor to create a professional CV in minutes",
    "builder.editor": "Editor",
    "builder.preview": "Preview",
    "builder.save": "Save",
    "builder.download": "Download PDF",
    "builder.sections": "Sections",
    "builder.sections.subtitle": "Add or edit sections of your CV",
    "builder.add.section": "Add a section",
    "builder.personal": "Personal information",
    "builder.experience": "Work experience",
    "builder.education": "Education",
    "builder.skills": "Skills",
    "builder.languages": "Languages",
    "builder.interests": "Interests",
    "builder.preview.title": "Preview of your CV",
    "builder.preview.subtitle": "Here's how your CV will look once downloaded",
    "modify.title": "Modify an existing CV",
    "modify.subtitle": "Upload your existing CV to transform it with our editor",
    "modify.upload": "Upload your CV",
    "modify.formats": "Accepted formats: PDF, Word (.docx, .doc)",
    "modify.drop": "Drag and drop your CV here or click to select",
    "modify.maxsize": "Maximum size: 5MB",
    "modify.browse": "Browse files",
    "modify.upload.btn": "Upload",
    "modify.uploading": "Uploading...",
    "modify.success": "Upload successful!",
    "modify.success.message": "Your CV has been uploaded successfully. We are analyzing its content.",
    "modify.redirect": "Redirecting to the CV editor in a few seconds...",
    "modify.error.size": "The file is too large. Maximum size is 5MB.",
    "modify.error.format": "Unsupported file format. Please upload a PDF or Word file.",
    "how.title": "How it works",
    "how.step1": "Upload your CV",
    "how.step1.desc": "Upload your existing CV in PDF or Word format.",
    "how.step2": "Our system analyzes it",
    "how.step2.desc": "Our smart tool automatically extracts information from your CV.",
    "how.step3": "Customize and improve",
    "how.step3.desc": "Use our editor to modify, improve and choose a new design.",
    "howworks.title": "How it works?",
    "howworks.description": "Create a perfect CV with our templates and their professional layouts.",
    "howworks.step1.title": "Select a CV template",
    "howworks.step1.description": "from our 35 customizable templates.",
    "howworks.step2.title": "Add pre-written content",
    "howworks.step2.description": "by experts (over 58,000 content pieces available).",
    "howworks.step3.title": "Download in PDF or Word format",
    "howworks.step3.description": "and start applying.",
    "pricing.title": "Simple and transparent pricing",
    "pricing.subtitle": "Choose the plan that suits your needs, with no surprises.",
    "pricing.monthly": "Monthly",
    "pricing.yearly": "Yearly",
    "pricing.discount": "(-20%)",
    "pricing.popular": "Most popular",
    "pricing.free": "Free",
    "pricing.free.desc": "To get started with the basics",
    "pricing.premium": "Premium",
    "pricing.premium.desc": "For serious job seekers",
    "pricing.student": "Student",
    "pricing.student.desc": "Special for students with ID",
    "pricing.per.month": "per month",
    "pricing.yearly.save": "Save 20% with yearly subscription",
    "pricing.free.btn": "Start for free",
    "pricing.premium.btn": "Subscribe now",
    "pricing.student.btn": "Check eligibility",
    "pricing.included": "Included in this plan:",
    "pricing.limitations": "Limitations:",
    "pricing.faq.title": "Frequently Asked Questions",
    "pricing.faq.more": "More information available in our help center.",
    "pricing.faq.others": "Do you have other questions? Contact our support team.",
    "pricing.faq.contact": "Contact support",
    "footer.copyright": "All rights reserved",
  },
  es: {
    "home.title": "Crea un CV profesional en pocos clics",
    "home.subtitle": "Una plataforma interactiva que te ayuda a crear un CV profesional adaptado a los requisitos de los reclutadores",
    "home.cta.start": "Comenzar gratis",
    "home.cta.modify": "Modificar un CV existente",
    "templates.title": "Explora nuestras plantillas de CV",
    "templates.subtitle": "Descubre nuestra colección completa de plantillas profesionales y creativas para hacer brillar tu CV",
    "templates.search": "Buscar una plantilla...",
    "templates.category.all": "Todas",
    "templates.category.professional": "Profesionales",
    "templates.category.creative": "Creativas",
    "templates.category.business": "Negocios",
    "templates.category.academic": "Académicas",
    "templates.category.minimalist": "Minimalistas",
    "templates.category.colorful": "Coloridas",
    "templates.category.modern": "Modernas",
    "templates.popular": "Popular",
    "templates.use": "Usar esta plantilla",
    "templates.notfound": "No se encontraron plantillas",
    "templates.notfound.subtitle": "Intenta con otros términos de búsqueda o filtros",
    "builder.title": "Crea tu CV",
    "builder.subtitle": "Utiliza nuestro editor para crear un CV profesional en minutos",
    "builder.editor": "Editor",
    "builder.preview": "Vista previa",
    "builder.save": "Guardar",
    "builder.download": "Descargar PDF",
    "builder.sections": "Secciones",
    "builder.sections.subtitle": "Añade o edita secciones de tu CV",
    "builder.add.section": "Añadir una sección",
    "builder.personal": "Información personal",
    "builder.experience": "Experiencia laboral",
    "builder.education": "Formación",
    "builder.skills": "Habilidades",
    "builder.languages": "Idiomas",
    "builder.interests": "Intereses",
    "builder.preview.title": "Vista previa de tu CV",
    "builder.preview.subtitle": "Así es como se verá tu CV una vez descargado",
    "modify.title": "Modificar un CV existente",
    "modify.subtitle": "Carga tu CV existente para transformarlo con nuestro editor",
    "modify.upload": "Cargar tu CV",
    "modify.formats": "Formatos aceptados: PDF, Word (.docx, .doc)",
    "modify.drop": "Arrastra y suelta tu CV aquí o haz clic para seleccionar",
    "modify.maxsize": "Tamaño máximo: 5MB",
    "modify.browse": "Explorar archivos",
    "modify.upload.btn": "Cargar",
    "modify.uploading": "Cargando...",
    "modify.success": "¡Carga exitosa!",
    "modify.success.message": "Tu CV ha sido cargado con éxito. Estamos analizando su contenido.",
    "modify.redirect": "Redirigiendo al editor de CV en unos segundos...",
    "modify.error.size": "El archivo es demasiado grande. El tamaño máximo es de 5MB.",
    "modify.error.format": "Formato de archivo no compatible. Por favor, carga un archivo PDF o Word.",
    "how.title": "Cómo funciona",
    "how.step1": "Carga tu CV",
    "how.step1.desc": "Carga tu CV existente en formato PDF o Word.",
    "how.step2": "Nuestro sistema lo analiza",
    "how.step2.desc": "Nuestra herramienta inteligente extrae automáticamente la información de tu CV.",
    "how.step3": "Personaliza y mejora",
    "how.step3.desc": "Utiliza nuestro editor para modificar, mejorar y elegir un nuevo diseño.",
    "howworks.title": "¿Cómo funciona?",
    "howworks.description": "Crea un CV perfecto gracias a nuestras plantillas y sus diseños profesionales.",
    "howworks.step1.title": "Selecciona una plantilla de CV",
    "howworks.step1.description": "entre nuestras 35 plantillas personalizables.",
    "howworks.step2.title": "Añade contenido pre-escrito",
    "howworks.step2.description": "por expertos (más de 58.000 contenidos disponibles).",
    "howworks.step3.title": "Descarga en formato PDF o Word",
    "howworks.step3.description": "y comienza a postularte.",
    "pricing.title": "Precios simples y transparentes",
    "pricing.subtitle": "Elige el plan que se adapte a tus necesidades, sin sorpresas.",
    "pricing.monthly": "Mensual",
    "pricing.yearly": "Anual",
    "pricing.discount": "(-20%)",
    "pricing.popular": "Más popular",
    "pricing.free": "Gratis",
    "pricing.free.desc": "Para comenzar con lo básico",
    "pricing.premium": "Premium",
    "pricing.premium.desc": "Para buscadores de empleo serios",
    "pricing.student": "Estudiante",
    "pricing.student.desc": "Especial para estudiantes con identificación",
    "pricing.per.month": "por mes",
    "pricing.yearly.save": "Ahorra un 20% con la suscripción anual",
    "pricing.free.btn": "Comenzar gratis",
    "pricing.premium.btn": "Suscribirse ahora",
    "pricing.student.btn": "Verificar elegibilidad",
    "pricing.included": "Incluido en este plan:",
    "pricing.limitations": "Limitaciones:",
    "pricing.faq.title": "Preguntas frecuentes",
    "pricing.faq.more": "Más información disponible en nuestro centro de ayuda.",
    "pricing.faq.others": "¿Tienes otras preguntas? Contacta a nuestro equipo de soporte.",
    "pricing.faq.contact": "Contactar soporte",
    "footer.copyright": "Todos los derechos reservados",
  },
  wo: {
    "home.title": "Defar sa CV bu pro ci natt yu néew",
    "home.subtitle": "Platforme bu lay dimbalé defar CV bu pro bu dëpp ci li ñi di liggeye di seet",
    "home.cta.start": "Tambali ak dara",
    "home.cta.modify": "Soppi CV bi nga am",
    "templates.title": "Seet sunu modèle yi",
    "templates.subtitle": "Seet sunu koleksióon bu mat sëkk si modèle yu pro ak yu rafet ngir rafetal sa CV",
    "templates.search": "Seet ab modèle...",
    "templates.category.all": "Yépp",
    "templates.category.professional": "Professionnel",
    "templates.category.creative": "Créatif",
    "templates.category.business": "Business",
    "templates.category.academic": "Académique",
    "templates.category.minimalist": "Minimalist",
    "templates.category.colorful": "Mel-melo",
    "templates.category.modern": "Modern",
    "templates.popular": "Lu gënë begg",
    "templates.use": "Jëfandikool modèle bii",
    "templates.notfound": "Giseeful benn modèle",
    "templates.notfound.subtitle": "Jéemël yeneen lafaz walla filtre",
    "builder.title": "Defar sa CV",
    "builder.subtitle": "Jëfandikool sunu éditeur ngir defar CV bu pro si ay simili",
    "builder.editor": "Éditeur",
    "builder.preview": "Wonelukaayu",
    "builder.save": "Denc",
    "builder.download": "Yebbi PDF",
    "builder.sections": "Xaaj yi",
    "builder.sections.subtitle": "Dolli walla soppi xaaj yi ci sa CV",
    "builder.add.section": "Dolli xaaj",
    "builder.personal": "Sa xibaar",
    "builder.experience": "Sa xam-xam liggéey",
    "builder.education": "Sa jàng",
    "builder.skills": "Sa kàttan",
    "builder.languages": "Làkk yi nga xam",
    "builder.interests": "Li nga bëgg",
    "builder.preview.title": "Wonelukaayu sa CV",
    "builder.preview.subtitle": "Nii lay mel sa CV bu pare",
    "modify.title": "Soppi CV bu nga am",
    "modify.subtitle": "Yebbiil sa CV ngir soppi ko ak sunu éditeur",
    "modify.upload": "Yebbi sa CV",
    "modify.formats": "Format yi nu nangul: PDF, Word (.docx, .doc)",
    "modify.drop": "Yebbiil sa CV fii walla klig ngir fal ko",
    "modify.maxsize": "Réeyaay bi gënë bari: 5MB",
    "modify.browse": "Seet fichier yi",
    "modify.upload.btn": "Yebbi",
    "modify.uploading": "Mi ngi yebbi...",
    "modify.success": "Yebbisi na bu baax!",
    "modify.success.message": "Sa CV yebbisi na. Nu ngi ko jàng.",
    "modify.redirect": "Di la yóbbu ci éditeur bi ci ay simili...",
    "modify.error.size": "Fichier bi dafa rëy. Li gënë bari mooy 5MB.",
    "modify.error.format": "Format bi baxul. Yebbil PDF walla fichier Word.",
    "how.title": "Nu muy doxe",
    "how.step1": "Yebbi sa CV",
    "how.step1.desc": "Yebbi sa CV bi nga am ci format PDF walla Word.",
    "how.step2": "Sunu système di ko jàng",
    "how.step2.desc": "Sunu jumtukaay bu xarañ di jële xibaar yi ci sa CV.",
    "how.step3": "Personalisé ak yéesal",
    "how.step3.desc": "Jëfandikool sunu éditeur ngir soppi, yesal ak fal beneen design.",
    "howworks.title": "Nu muy doxe?",
    "howworks.description": "Defar CV bu mat sëkk ak sunu modèle yi ak seen mël-mël bu pro.",
    "howworks.step1.title": "Tanne ab modèle CV",
    "howworks.step1.description": "ci sunu 35 modèle yu ken mën soppi.",
    "howworks.step2.title": "Dolli mbind yu ñu bind",
    "howworks.step2.description": "yu ñu xam liggéey bi bind (lu ëpp 58 000 mbind).",
    "howworks.step3.title": "Yebbi ko ci format PDF walla Word",
    "howworks.step3.description": "te tambali di wut liggéey.",
    "pricing.title": "Njëg yu wóor te leer",
    "pricing.subtitle": "Tannel plan bi la mënal, ak yëf yu baax.",
    "pricing.monthly": "Weer bu nekk",
    "pricing.yearly": "At mu nekk",
    "pricing.discount": "(-20%)",
    "pricing.popular": "Bu ñu gënë begg",
    "pricing.free": "Amul njëg",
    "pricing.free.desc": "Ngir tambali ak lu néew",
    "pricing.premium": "Premium",
    "pricing.premium.desc": "Ngir ñi di wut liggéey bu baax",
    "pricing.student": "Étudiant",
    "pricing.student.desc": "Spécial ngir étudiant yi am kart",
    "pricing.per.month": "ci weer",
    "pricing.yearly.save": "Waaññi 20% ak abonnement bu at mu nekk",
    "pricing.free.btn": "Tambali ak dara",
    "pricing.premium.btn": "Abonné leegi",
    "pricing.student.btn": "Seet bu fekkoon",
    "pricing.included": "Li ñu boole ci plan bi:",
    "pricing.limitations": "Digënté yi:",
    "pricing.faq.title": "Laaj yi ñuy laaj lu bari",
    "pricing.faq.more": "Xibaar yu gënë bari ci sunu centre daid.",
    "pricing.faq.others": "Dangay am yeneen laaj? Jokkool ak sunu équipe ndimbal.",
    "pricing.faq.contact": "Jokkoo ndimbal",
    "footer.copyright": "Sañ-sañ yépp am nañoo ko",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem("language");
    return (savedLanguage as Language) || "fr";
  });

  const [currency, setCurrencyState] = useState<Currency>(() => {
    const savedCurrency = localStorage.getItem("currency");
    return (savedCurrency as Currency) || currencyMap[language as Language];
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
    // Only update currency if user hasn't manually set it
    const userSetCurrency = localStorage.getItem("userSetCurrency");
    if (!userSetCurrency) {
      setCurrency(currencyMap[lang]);
    }
  };

  const setCurrency = (curr: Currency) => {
    setCurrencyState(curr);
    localStorage.setItem("currency", curr);
    localStorage.setItem("userSetCurrency", "true");
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, currency, setCurrency, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const getCurrencySymbol = (currency: Currency) => {
  return currencySymbols[currency];
};

export const getLanguageName = (code: Language) => {
  return languageMap[code];
};
