// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exmdhxkzdajqdsfzqjsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bWRoeGt6ZGFqcWRzZnpxanNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTQ0MjUsImV4cCI6MjA2MDM3MDQyNX0.Auz9rOJCn1_UBwfk9FkFe1ZgzzuBsmcgMpqZuGCsQ5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);